# Generated by Django 2.0.2 on 2018-03-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('createdOn', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('product_area', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Policies'), (2, 'Billing'), (3, 'Claims'), (4, 'Reports')], null=True)),
                ('feat_priority', models.PositiveIntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feature.Client')),
            ],
        ),
    ]
