# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('product_area', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Policies'), (2, 'Billing'), (3, 'Claims'), (4, 'Reports')], null=True)),
            ],
        ),
    ]
