# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feat_priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'high'), (2, 'medium'), (3, 'low')], null=True),
        ),
    ]
