# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_feature_feat_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('createdOn', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='feat_priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], null=True),
        ),
    ]
