# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_auto_20180222_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
