# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0004_auto_20180222_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='client',
            field=models.ManyToManyField(to='feature.Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='createdOn',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
