# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_auto_20180222_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='client',
        ),
        migrations.AddField(
            model_name='feature',
            name='client',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='feature.Client'),
            preserve_default=False,
        ),
    ]
