# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0007_auto_20180222_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=50),
        ),
    ]
